### ISSUE TITLE
Maintenance Status?

### ISSUE THREAD

**Issue by MarkusWendorf** [virtualidentityag/quality-gate#469]
Hello there,

Is this repository still maintained and should it be used? 
The @virtualidentity/quality-gate@1.0.1 is up to date right? (replacing the biotope one)

Thanks

**Comment by ctmm** [comment]
> Is this repository still maintained and should it be used?
Yes

> The @virtualidentity/quality-gate@1.0.1 is up to date right?
Yes. Main changes are:

	- Retired Biotope namespace
	- Updated deprecated packages
	- Made Typescript a peer dependency so it's easily upgradable
