### ISSUE TITLE
update stylelint plugin in readme

### ISSUE THREAD

**Issue by christophsaile** [virtualidentityag/quality-gate#553]
Todo:
Please update the referenced stylelint plugin in the readme https://github.com/virtualidentityag/quality-gate#vscode.

Reason:
Currently the readme suggests to use the plugin: "hex-ci.stylelint-plus". This plugin was updated the last time on 06/09/2021 and leads to an error described in this issue:
https://github.com/stylelint/vscode-stylelint/issues/360

I would suggest to update the reference to the official stylelint plugin for VSCode:
stylelint.vscode-stylelint

**Comment by mariohamann** [comment]
Done. Thx. ❤️
